name: Preview on vercel

on:
  push:
    branches:
      - dev
  pull_request:

jobs:
  preview:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: amondnet/vercel-action@v25
        id: vercel-deploy
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID}}
          vercel-project-id: ${{ secrets.PROJECT_ID}}
          alias-domains: 'preview-buon18.vercel.app'
      - name: Output the preview URL
        run: |
          echo ${{ steps.vercel-deploy.outputs.preview-url }}